/**
 * Standard CBSE curriculum presets with formal subject codes, mark split schemas,
 * and realistic NCERT/CBSE chapter lists.
 */

export const CBSE_SPLIT_PRESETS = {
  "80_20": {
    split_type: "80_20",
    theory_marks: 80,
    practical_marks: 0,
    internal_marks: 20,
    total_marks: 100,
    label: "80 Theory + 20 Internal Assessment",
  },
  "70_30": {
    split_type: "70_30",
    theory_marks: 70,
    practical_marks: 30,
    internal_marks: 0,
    total_marks: 100,
    label: "70 Theory + 30 Practical/Lab",
  },
  "50_50": {
    split_type: "50_50",
    theory_marks: 50,
    practical_marks: 50,
    internal_marks: 0,
    total_marks: 100,
    label: "50 Theory + 50 Practical / Skill",
  },
  "100_0": {
    split_type: "100_0",
    theory_marks: 100,
    practical_marks: 0,
    internal_marks: 0,
    total_marks: 100,
    label: "100 Theory (No Practical)",
  },
};

export const CBSE_SUBJECT_PRESETS = [
  // Class 9 & 10 Secondary Presets
  {
    grade_range: [9, 10],
    code: "041",
    name: "Mathematics (Standard)",
    subject_type: "core",
    split_type: "80_20",
    theory_marks: 80,
    practical_marks: 0,
    internal_marks: 20,
    total_marks: 100,
    pass_marks: 33,
    periods_per_week: 7,
    description: "CBSE Class 10 Standard Mathematics curriculum covering Algebra, Geometry, Trigonometry, and Statistics.",
    default_chapters: [
      { chapter_number: 1, title: "Real Numbers", term: "Term 1", planned_periods: 8 },
      { chapter_number: 2, title: "Polynomials", term: "Term 1", planned_periods: 8 },
      { chapter_number: 3, title: "Pair of Linear Equations in Two Variables", term: "Term 1", planned_periods: 10 },
      { chapter_number: 4, title: "Quadratic Equations", term: "Term 1", planned_periods: 10 },
      { chapter_number: 5, title: "Arithmetic Progressions", term: "Term 1", planned_periods: 8 },
      { chapter_number: 6, title: "Triangles", term: "Term 1", planned_periods: 12 },
      { chapter_number: 7, title: "Coordinate Geometry", term: "Term 2", planned_periods: 8 },
      { chapter_number: 8, title: "Introduction to Trigonometry", term: "Term 2", planned_periods: 10 },
      { chapter_number: 9, title: "Some Applications of Trigonometry", term: "Term 2", planned_periods: 8 },
      { chapter_number: 10, title: "Circles", term: "Term 2", planned_periods: 8 },
      { chapter_number: 11, title: "Areas Related to Circles", term: "Term 2", planned_periods: 8 },
      { chapter_number: 12, title: "Surface Areas and Volumes", term: "Term 2", planned_periods: 10 },
      { chapter_number: 13, title: "Statistics", term: "Term 2", planned_periods: 10 },
      { chapter_number: 14, title: "Probability", term: "Term 2", planned_periods: 6 },
    ],
  },
  {
    grade_range: [9, 10],
    code: "086",
    name: "Science",
    subject_type: "core",
    split_type: "80_20",
    theory_marks: 80,
    practical_marks: 0,
    internal_marks: 20,
    total_marks: 100,
    pass_marks: 33,
    periods_per_week: 7,
    description: "CBSE Science curriculum encompassing Physics, Chemistry, and Biology.",
    default_chapters: [
      { chapter_number: 1, title: "Chemical Reactions and Equations", term: "Term 1", planned_periods: 8 },
      { chapter_number: 2, title: "Acids, Bases and Salts", term: "Term 1", planned_periods: 8 },
      { chapter_number: 3, title: "Metals and Non-metals", term: "Term 1", planned_periods: 10 },
      { chapter_number: 4, title: "Carbon and its Compounds", term: "Term 1", planned_periods: 10 },
      { chapter_number: 5, title: "Life Processes", term: "Term 1", planned_periods: 12 },
      { chapter_number: 6, title: "Control and Coordination", term: "Term 1", planned_periods: 8 },
      { chapter_number: 7, title: "How do Organisms Reproduce?", term: "Term 2", planned_periods: 10 },
      { chapter_number: 8, title: "Heredity and Evolution", term: "Term 2", planned_periods: 8 },
      { chapter_number: 9, title: "Light – Reflection and Refraction", term: "Term 2", planned_periods: 12 },
      { chapter_number: 10, title: "The Human Eye and the Colourful World", term: "Term 2", planned_periods: 8 },
      { chapter_number: 11, title: "Electricity", term: "Term 2", planned_periods: 12 },
      { chapter_number: 12, title: "Magnetic Effects of Electric Current", term: "Term 2", planned_periods: 10 },
      { chapter_number: 13, title: "Our Environment", term: "Term 2", planned_periods: 6 },
    ],
  },
  {
    grade_range: [9, 10],
    code: "087",
    name: "Social Science",
    subject_type: "core",
    split_type: "80_20",
    theory_marks: 80,
    practical_marks: 0,
    internal_marks: 20,
    total_marks: 100,
    pass_marks: 33,
    periods_per_week: 6,
    description: "History, Geography, Democratic Politics, and Economics.",
    default_chapters: [
      { chapter_number: 1, title: "The Rise of Nationalism in Europe", term: "Term 1", planned_periods: 8 },
      { chapter_number: 2, title: "Nationalism in India", term: "Term 1", planned_periods: 10 },
      { chapter_number: 3, title: "Resources and Development", term: "Term 1", planned_periods: 6 },
      { chapter_number: 4, title: "Forest and Wildlife Resources", term: "Term 1", planned_periods: 6 },
      { chapter_number: 5, title: "Power Sharing & Federalism", term: "Term 1", planned_periods: 8 },
      { chapter_number: 6, title: "Development (Economics)", term: "Term 1", planned_periods: 6 },
      { chapter_number: 7, title: "Sectors of the Indian Economy", term: "Term 2", planned_periods: 8 },
      { chapter_number: 8, title: "Money and Credit", term: "Term 2", planned_periods: 8 },
      { chapter_number: 9, title: "Minerals and Energy Resources", term: "Term 2", planned_periods: 8 },
      { chapter_number: 10, title: "Manufacturing Industries", term: "Term 2", planned_periods: 8 },
      { chapter_number: 11, title: "Political Parties", term: "Term 2", planned_periods: 6 },
      { chapter_number: 12, title: "Outcomes of Democracy", term: "Term 2", planned_periods: 6 },
    ],
  },
  {
    grade_range: [9, 10],
    code: "184",
    name: "English Language and Literature",
    subject_type: "language",
    split_type: "80_20",
    theory_marks: 80,
    practical_marks: 0,
    internal_marks: 20,
    total_marks: 100,
    pass_marks: 33,
    periods_per_week: 6,
    description: "Reading skills, writing skills, grammar, and literature prose/poetry.",
    default_chapters: [
      { chapter_number: 1, title: "A Letter to God & Dust of Snow", term: "Term 1", planned_periods: 6 },
      { chapter_number: 2, title: "Nelson Mandela: Long Walk to Freedom", term: "Term 1", planned_periods: 6 },
      { chapter_number: 3, title: "Two Stories about Flying", term: "Term 1", planned_periods: 6 },
      { chapter_number: 4, title: "From the Diary of Anne Frank", term: "Term 1", planned_periods: 6 },
      { chapter_number: 5, title: "A Triumph of Surgery", term: "Term 1", planned_periods: 5 },
      { chapter_number: 6, title: "The Thief's Story & The Midnight Visitor", term: "Term 2", planned_periods: 6 },
      { chapter_number: 7, title: "Glimpses of India & Fog", term: "Term 2", planned_periods: 6 },
      { chapter_number: 8, title: "Madam Rides the Bus", term: "Term 2", planned_periods: 6 },
      { chapter_number: 9, title: "The Sermon at Benares & The Proposal", term: "Term 2", planned_periods: 8 },
      { chapter_number: 10, title: "The Book that Saved the Earth", term: "Term 2", planned_periods: 5 },
    ],
  },
  {
    grade_range: [9, 10],
    code: "002",
    name: "Hindi Course-A",
    subject_type: "language",
    split_type: "80_20",
    theory_marks: 80,
    practical_marks: 0,
    internal_marks: 20,
    total_marks: 100,
    pass_marks: 33,
    periods_per_week: 6,
    description: "Hindi prose, poetry, vyakaran, and anuchhed/patra lekhan.",
    default_chapters: [
      { chapter_number: 1, title: "पद (सूरदास)", term: "Term 1", planned_periods: 6 },
      { chapter_number: 2, title: "राम-लक्ष्मण-परशुराम संवाद", term: "Term 1", planned_periods: 8 },
      { chapter_number: 3, title: "नेताजी का चश्मा", term: "Term 1", planned_periods: 6 },
      { chapter_number: 4, title: "बालगोबिन भगत", term: "Term 1", planned_periods: 6 },
      { chapter_number: 5, title: "माता का आँचल (कृतिका)", term: "Term 1", planned_periods: 6 },
      { chapter_number: 6, title: "उत्साह और अट नहीं रही है", term: "Term 2", planned_periods: 6 },
      { chapter_number: 7, title: "यह दंतुरित मुसकान / फसल", term: "Term 2", planned_periods: 6 },
      { chapter_number: 8, title: "लखनवी अंदाज़", term: "Term 2", planned_periods: 6 },
      { chapter_number: 9, title: "एक कहानी यह भी", term: "Term 2", planned_periods: 6 },
      { chapter_number: 10, title: "साना-साना हाथ जोड़ि (कृतिका)", term: "Term 2", planned_periods: 6 },
    ],
  },
  {
    grade_range: [9, 10],
    code: "402",
    name: "Information Technology",
    subject_type: "vocational",
    split_type: "50_50",
    theory_marks: 50,
    practical_marks: 50,
    internal_marks: 0,
    total_marks: 100,
    pass_marks: 33,
    periods_per_week: 4,
    description: "Skill elective covering digital documentation, spreadsheet, DBMS, and web applications.",
    default_chapters: [
      { chapter_number: 1, title: "Communication & Self-Management Skills", term: "Term 1", planned_periods: 6 },
      { chapter_number: 2, title: "Digital Documentation (Advanced)", term: "Term 1", planned_periods: 10 },
      { chapter_number: 3, title: "Electronic Spreadsheet (Advanced)", term: "Term 1", planned_periods: 10 },
      { chapter_number: 4, title: "Database Management System (RDBMS)", term: "Term 2", planned_periods: 12 },
      { chapter_number: 5, title: "Web Applications and Security", term: "Term 2", planned_periods: 8 },
    ],
  },

  // Class 11 & 12 Senior Secondary Presets
  {
    grade_range: [11, 12],
    code: "042",
    name: "Physics",
    subject_type: "core",
    split_type: "70_30",
    theory_marks: 70,
    practical_marks: 30,
    internal_marks: 0,
    total_marks: 100,
    pass_marks: 33,
    periods_per_week: 8,
    description: "Core Physics including Electrostatics, Magnetism, Optics, Modern Physics, and Laboratory experiments.",
    default_chapters: [
      { chapter_number: 1, title: "Electric Charges and Fields", term: "Term 1", planned_periods: 10 },
      { chapter_number: 2, title: "Electrostatic Potential and Capacitance", term: "Term 1", planned_periods: 10 },
      { chapter_number: 3, title: "Current Electricity", term: "Term 1", planned_periods: 12 },
      { chapter_number: 4, title: "Moving Charges and Magnetism", term: "Term 1", planned_periods: 10 },
      { chapter_number: 5, title: "Magnetism and Matter", term: "Term 1", planned_periods: 6 },
      { chapter_number: 6, title: "Electromagnetic Induction & AC", term: "Term 1", planned_periods: 12 },
      { chapter_number: 7, title: "Electromagnetic Waves", term: "Term 2", planned_periods: 4 },
      { chapter_number: 8, title: "Ray Optics and Optical Instruments", term: "Term 2", planned_periods: 12 },
      { chapter_number: 9, title: "Wave Optics", term: "Term 2", planned_periods: 10 },
      { chapter_number: 10, title: "Dual Nature of Radiation and Matter", term: "Term 2", planned_periods: 8 },
      { chapter_number: 11, title: "Atoms and Nuclei", term: "Term 2", planned_periods: 10 },
      { chapter_number: 12, title: "Semiconductor Electronics", term: "Term 2", planned_periods: 10 },
    ],
  },
  {
    grade_range: [11, 12],
    code: "043",
    name: "Chemistry",
    subject_type: "core",
    split_type: "70_30",
    theory_marks: 70,
    practical_marks: 30,
    internal_marks: 0,
    total_marks: 100,
    pass_marks: 33,
    periods_per_week: 8,
    description: "Physical, Inorganic, and Organic Chemistry with laboratory titrations and qualitative analysis.",
    default_chapters: [
      { chapter_number: 1, title: "Solutions", term: "Term 1", planned_periods: 10 },
      { chapter_number: 2, title: "Electrochemistry", term: "Term 1", planned_periods: 12 },
      { chapter_number: 3, title: "Chemical Kinetics", term: "Term 1", planned_periods: 10 },
      { chapter_number: 4, title: "The d- and f-Block Elements", term: "Term 1", planned_periods: 8 },
      { chapter_number: 5, title: "Coordination Compounds", term: "Term 1", planned_periods: 10 },
      { chapter_number: 6, title: "Haloalkanes and Haloarenes", term: "Term 2", planned_periods: 10 },
      { chapter_number: 7, title: "Alcohols, Phenols and Ethers", term: "Term 2", planned_periods: 10 },
      { chapter_number: 8, title: "Aldehydes, Ketones and Carboxylic Acids", term: "Term 2", planned_periods: 12 },
      { chapter_number: 9, title: "Amines", term: "Term 2", planned_periods: 8 },
      { chapter_number: 10, title: "Biomolecules", term: "Term 2", planned_periods: 8 },
    ],
  },
  {
    grade_range: [11, 12],
    code: "044",
    name: "Biology",
    subject_type: "core",
    split_type: "70_30",
    theory_marks: 70,
    practical_marks: 30,
    internal_marks: 0,
    total_marks: 100,
    pass_marks: 33,
    periods_per_week: 8,
    description: "Reproduction, Genetics, Evolution, Biotechnology, and Ecology with lab dissections/slides.",
    default_chapters: [
      { chapter_number: 1, title: "Sexual Reproduction in Flowering Plants", term: "Term 1", planned_periods: 10 },
      { chapter_number: 2, title: "Human Reproduction & Reproductive Health", term: "Term 1", planned_periods: 12 },
      { chapter_number: 3, title: "Principles of Inheritance and Variation", term: "Term 1", planned_periods: 12 },
      { chapter_number: 4, title: "Molecular Basis of Inheritance", term: "Term 1", planned_periods: 12 },
      { chapter_number: 5, title: "Evolution", term: "Term 1", planned_periods: 8 },
      { chapter_number: 6, title: "Human Health and Disease", term: "Term 2", planned_periods: 8 },
      { chapter_number: 7, title: "Microbes in Human Welfare", term: "Term 2", planned_periods: 6 },
      { chapter_number: 8, title: "Biotechnology: Principles and Processes", term: "Term 2", planned_periods: 8 },
      { chapter_number: 9, title: "Biotechnology and its Applications", term: "Term 2", planned_periods: 8 },
      { chapter_number: 10, title: "Organisms, Populations and Ecosystem", term: "Term 2", planned_periods: 10 },
      { chapter_number: 11, title: "Biodiversity and Conservation", term: "Term 2", planned_periods: 6 },
    ],
  },
  {
    grade_range: [11, 12],
    code: "083",
    name: "Computer Science",
    subject_type: "elective",
    split_type: "70_30",
    theory_marks: 70,
    practical_marks: 30,
    internal_marks: 0,
    total_marks: 100,
    pass_marks: 33,
    periods_per_week: 6,
    description: "Python Programming, Data Structures, Computer Networks, and SQL Databases.",
    default_chapters: [
      { chapter_number: 1, title: "Python Revision Tour & Functions", term: "Term 1", planned_periods: 10 },
      { chapter_number: 2, title: "File Handling in Python (Text, Binary, CSV)", term: "Term 1", planned_periods: 12 },
      { chapter_number: 3, title: "Using Python Libraries", term: "Term 1", planned_periods: 6 },
      { chapter_number: 4, title: "Data Structures: Linear List, Stack using List", term: "Term 1", planned_periods: 10 },
      { chapter_number: 5, title: "Computer Networks & Protocols", term: "Term 2", planned_periods: 12 },
      { chapter_number: 6, title: "Database Management & SQL Queries", term: "Term 2", planned_periods: 14 },
      { chapter_number: 7, title: "Interface Python with SQL Database", term: "Term 2", planned_periods: 10 },
      { chapter_number: 8, title: "Societal Impacts & Cyber Law", term: "Term 2", planned_periods: 6 },
    ],
  },
  {
    grade_range: [11, 12],
    code: "055",
    name: "Accountancy",
    subject_type: "core",
    split_type: "80_20",
    theory_marks: 80,
    practical_marks: 0,
    internal_marks: 20,
    total_marks: 100,
    pass_marks: 33,
    periods_per_week: 7,
    description: "Accounting for Partnership Firms, Companies, and Financial Statement Analysis.",
    default_chapters: [
      { chapter_number: 1, title: "Accounting for Partnership: Fundamentals", term: "Term 1", planned_periods: 12 },
      { chapter_number: 2, title: "Goodwill: Nature and Valuation", term: "Term 1", planned_periods: 6 },
      { chapter_number: 3, title: "Change in Profit Sharing Ratio", term: "Term 1", planned_periods: 8 },
      { chapter_number: 4, title: "Admission of a Partner", term: "Term 1", planned_periods: 14 },
      { chapter_number: 5, title: "Retirement and Death of a Partner", term: "Term 1", planned_periods: 12 },
      { chapter_number: 6, title: "Dissolution of Partnership Firm", term: "Term 1", planned_periods: 10 },
      { chapter_number: 7, title: "Accounting for Share Capital", term: "Term 2", planned_periods: 16 },
      { chapter_number: 8, title: "Issue and Redemption of Debentures", term: "Term 2", planned_periods: 10 },
      { chapter_number: 9, title: "Financial Statements of a Company", term: "Term 2", planned_periods: 8 },
      { chapter_number: 10, title: "Accounting Ratios & Cash Flow Statement", term: "Term 2", planned_periods: 14 },
    ],
  },

  // Foundation Classes (1-8)
  {
    grade_range: [1, 2, 3, 4, 5, 6, 7, 8],
    code: "MTH",
    name: "Mathematics",
    subject_type: "core",
    split_type: "80_20",
    theory_marks: 80,
    practical_marks: 0,
    internal_marks: 20,
    total_marks: 100,
    pass_marks: 33,
    periods_per_week: 6,
    description: "Foundational and Middle School Mathematics curriculum.",
    default_chapters: [
      { chapter_number: 1, title: "Numbers & Number Systems", term: "Term 1", planned_periods: 10 },
      { chapter_number: 2, title: "Basic Arithmetic Operations & Fractions", term: "Term 1", planned_periods: 12 },
      { chapter_number: 3, title: "Decimals and Factors", term: "Term 1", planned_periods: 10 },
      { chapter_number: 4, title: "Basic Geometry & Shapes", term: "Term 1", planned_periods: 10 },
      { chapter_number: 5, title: "Mensuration & Perimeter/Area", term: "Term 2", planned_periods: 12 },
      { chapter_number: 6, title: "Algebraic Expressions Intro", term: "Term 2", planned_periods: 10 },
      { chapter_number: 7, title: "Ratio, Proportion & Percentage", term: "Term 2", planned_periods: 10 },
      { chapter_number: 8, title: "Data Handling & Graphs", term: "Term 2", planned_periods: 8 },
    ],
  },
  {
    grade_range: [1, 2, 3, 4, 5, 6, 7, 8],
    code: "SCI",
    name: "General Science",
    subject_type: "core",
    split_type: "80_20",
    theory_marks: 80,
    practical_marks: 0,
    internal_marks: 20,
    total_marks: 100,
    pass_marks: 33,
    periods_per_week: 6,
    description: "Environmental and Natural Sciences for Primary and Middle schools.",
    default_chapters: [
      { chapter_number: 1, title: "Food: Sources and Components", term: "Term 1", planned_periods: 8 },
      { chapter_number: 2, title: "Sorting Materials into Groups", term: "Term 1", planned_periods: 8 },
      { chapter_number: 3, title: "Separation of Substances", term: "Term 1", planned_periods: 8 },
      { chapter_number: 4, title: "Getting to Know Plants", term: "Term 1", planned_periods: 10 },
      { chapter_number: 5, title: "Body Movements & Skeleton", term: "Term 2", planned_periods: 8 },
      { chapter_number: 6, title: "Living Organisms and their Surroundings", term: "Term 2", planned_periods: 10 },
      { chapter_number: 7, title: "Motion and Measurement of Distances", term: "Term 2", planned_periods: 8 },
      { chapter_number: 8, title: "Light, Shadows and Reflections", term: "Term 2", planned_periods: 8 },
      { chapter_number: 9, title: "Electricity and Circuits", term: "Term 2", planned_periods: 8 },
    ],
  },
];

